cache:
    - bundler
osx_image: xcode7.2
language: objective-c
sudo: false
branches:
  only:
    - master
    - /^release-.*$/
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3
script: ./ci/script.sh
after_success: ./ci/after_success.sh
