osx_image: xcode7.2
language: objective-c
sudo: false
branches:
  only:
    - master
    - /^release-.*$/
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
before_install: ./ci/before_install.sh
script: ./ci/script.sh
after_success: ./slather.sh
